version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '5000:5000'
    environment:
      DB__HOSTNAME: db
      DB__USERNAME: ethapi
      DB__PASSWORD: ""
      DB__DATABASE: ethapi
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:12
    restart: always
    container_name: eth-db
    environment:
      POSTGRES_USER: ethapi
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: ethapi
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
